// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL as string | undefined)?.trim() ?? '';
/** Prefer publishable key name; VITE_SUPABASE_ANON_KEY is a common Vercel alias. */
const SUPABASE_PUBLISHABLE_KEY =
  (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined)?.trim() ||
  (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined)?.trim() ||
  '';

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error(
    "[Clasly] Missing Supabase env: set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY) on the build host (e.g. Vercel).",
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    storageKey: 'clasly-auth',
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
    heartbeatIntervalMs: 25000,
    reconnectAfterMs: (tries: number) =>
      [500, 1000, 2000, 4000, 8000, 15000][Math.min(tries, 5)],
  },
});

/**
 * Remove all Supabase realtime channels.
 * Useful before navigating away from a live view to prevent orphaned channels
 * from consuming server-side Realtime slots.
 */
export function removeAllChannels(): void {
  const channels = supabase.getChannels();
  for (const ch of channels) {
    supabase.removeChannel(ch);
  }
}